// This file is generated by npm run icons

export type IconName =
	| "archive"
	| "big-play"
	| "check"
	| "chevronDown"
	| "clock"
	| "desktop"
	| "dotsHorizontal"
	| "edit"
	| "externalLink"
	| "github"
	| "link"
	| "minus"
	| "moon"
	| "plus"
	| "search"
	| "star"
	| "sun"
	| "trash"
	| "view";
